### ISSUE TITLE
Incompatibility between Extradite and vim-airline: missing commit timestamp

### ISSUE THREAD

**Issue by benichu** [benichu/2ret-vim#7]
The status line should be like this: ![](https://www.dropbox.com/s/psxj7270jkwsyq5/1._vim_2015-09-20_19-04-37.png?dl=1)
But instead it is like that: ![](https://www.dropbox.com/s/462npb8hj0tcvv0/1._vim_2015-09-20_19-05-39.png?dl=1)

**Comment by benichu** [comment]
@AlainPilon If you have any idea...

**Comment by AlainPilon** [comment]
je vais me faire un fork pour checker. C'est assez simple du coté de extradite, je pense que c'est du côté de airline qu'il y a un bug. il faut juste que je figure comment me faire un env de dev avec des plugins qui sont déjà dans 2ret-vim.

**Comment by benichu** [comment]
Tu clones ton fork dans `~/.2ret-vim` et voila.

**Comment by AlainPilon** [comment]
ok, je fais un peu de job et je check ca :-)

**Comment by benichu** [comment]
Fixed by this https://github.com/int3/vim-extradite/issues/37#issuecomment-142313046
run `vim +PluginInstall! +PluginClean +qall` to apply updates form `vim-extradite`
